Bay.loadComponent('components/loading-hint.html')
Bay.loadComponent('components/slider-round.html')
Bay.loadComponent('components/link-github.html')
Bay.loadComponent('components/settings/settings-category.html', window.SettingsCategory)
Bay.loadComponent('components/settings/settings-toggle.html', window.Setting)
